# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x06\x63lient\"\x1f\n\x10GetLeaderRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"4\n\x11GetLeaderResponse\x12\x0e\n\x06leader\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x14GetLeaderInfoRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"8\n\x15GetLeaderInfoResponse\x12\x0e\n\x06leader\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"-\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bSetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x80\x02\n\x06\x63lient\x12\x42\n\tGetLeader\x12\x18.client.GetLeaderRequest\x1a\x19.client.GetLeaderResponse\"\x00\x12N\n\rGetLeaderInfo\x12\x1c.client.GetLeaderInfoRequest\x1a\x1d.client.GetLeaderInfoResponse\"\x00\x12\x30\n\x03Get\x12\x12.client.GetRequest\x1a\x13.client.GetResponse\"\x00\x12\x30\n\x03Set\x12\x12.client.SetRequest\x1a\x13.client.SetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETLEADERREQUEST']._serialized_start=24
  _globals['_GETLEADERREQUEST']._serialized_end=55
  _globals['_GETLEADERRESPONSE']._serialized_start=57
  _globals['_GETLEADERRESPONSE']._serialized_end=109
  _globals['_GETLEADERINFOREQUEST']._serialized_start=111
  _globals['_GETLEADERINFOREQUEST']._serialized_end=146
  _globals['_GETLEADERINFORESPONSE']._serialized_start=148
  _globals['_GETLEADERINFORESPONSE']._serialized_end=204
  _globals['_GETREQUEST']._serialized_start=206
  _globals['_GETREQUEST']._serialized_end=231
  _globals['_GETRESPONSE']._serialized_start=233
  _globals['_GETRESPONSE']._serialized_end=278
  _globals['_SETREQUEST']._serialized_start=280
  _globals['_SETREQUEST']._serialized_end=320
  _globals['_SETRESPONSE']._serialized_start=322
  _globals['_SETRESPONSE']._serialized_end=352
  _globals['_CLIENT']._serialized_start=355
  _globals['_CLIENT']._serialized_end=611
# @@protoc_insertion_point(module_scope)
