# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Node.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nNode.proto\x12\x04Node\"R\n\x0bvoteRequest\x12\x0e\n\x06\x63_term\x18\x01 \x01(\x03\x12\x0c\n\x04\x63_id\x18\x02 \x01(\x03\x12\x11\n\tc_log_len\x18\x03 \x01(\x03\x12\x12\n\nc_log_term\x18\x04 \x01(\x03\">\n\x0cvoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07granted\x18\x02 \x01(\x08\x12\x0f\n\x07node_id\x18\x03 \x01(\x03\"q\n\nlogRequest\x12\x0c\n\x04l_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x63_term\x18\x02 \x01(\x03\x12\x10\n\x08pref_len\x18\x03 \x01(\x03\x12\x11\n\tpref_term\x18\x04 \x01(\x03\x12\x0e\n\x06suffix\x18\x06 \x03(\t\x12\x10\n\x08l_commit\x18\x05 \x01(\x03\"F\n\x0blogResponse\x12\x0c\n\x04\x66_id\x18\x01 \x01(\x03\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x03\x12\x0e\n\x06sucess\x18\x04 \x01(\x08\x32o\n\x04Node\x12\x34\n\x0brequestVote\x12\x11.Node.voteRequest\x1a\x12.Node.voteResponse\x12\x31\n\nrequestLog\x12\x10.Node.logRequest\x1a\x11.Node.logResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=102
  _globals['_VOTERESPONSE']._serialized_start=104
  _globals['_VOTERESPONSE']._serialized_end=166
  _globals['_LOGREQUEST']._serialized_start=168
  _globals['_LOGREQUEST']._serialized_end=281
  _globals['_LOGRESPONSE']._serialized_start=283
  _globals['_LOGRESPONSE']._serialized_end=353
  _globals['_NODE']._serialized_start=355
  _globals['_NODE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
